//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineElectionSystem_FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constitution
    {
        public int Id { get; set; }
        public string ConstitutionCode { get; set; }
        public string ConstitutionCity { get; set; }
        public int TotalNumberOfVoters { get; set; }
        public int TotalVotesCasted { get; set; }
        public int TotalCandidates { get; set; }
        public String WinningCandidate { get; set; }
        public List<Candidate> Candidates { get; set; }
    }
}
