//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineElectionSystem_FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Election_Votes_Candidate
    {
        public int Id { get; set; }
        public Nullable<int> ConstitutionId { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<int> VoterId { get; set; }
    }
}
