//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineElectionSystem_FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoterSentiment
    {
        public int Id { get; set; }
        public int VoterId { get; set; }
        public string Sentiment { get; set; }
        public int Rating { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public String VoterCNIC { get; set; }
        public String CandidateName { get; set; }
        public String Constituency { get; set; }
    }
}
