//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineElectionSystem_FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voter
    {
        public int Id { get; set; }
        public string CNIC { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string CurrentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string Constitute { get; set; }
    }
}
